version: "3"

services:
  proxy:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - default
      - proxy_manager

  verdaccio:
    image: verdaccio/verdaccio
    restart: unless-stopped
    volumes:
      - verdaccio_storage:/verdaccio/storage
      - ./verdaccio/conf:/verdaccio/conf
      - ./verdaccio/plugins:/verdaccio/plugins

networks:
  proxy_manager:
    driver: bridge
    name: proxy_manager

volumes:
  verdaccio_storage:
